// <copyright file="GPGSIds.cs" company="Google Inc.">
// Copyright (C) 2015 Google Inc. All Rights Reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//    limitations under the License.
// </copyright>

///
/// This file is automatically generated DO NOT EDIT!
///
/// These are the constants defined in the Play Games Console for Game Services
/// Resources.
///


public static class GPGSlds
{
        public const string achievement_mirror_my_beautiful_mirror = "CgkIuv6JzuIEEAIQBQ"; // <GPGSID>
        public const string achievement_unblocked_track = "CgkIuv6JzuIEEAIQBw"; // <GPGSID>
        public const string achievement_care_under_surveillance = "CgkIuv6JzuIEEAIQCA"; // <GPGSID>
        public const string achievement_spaceships_commander = "CgkIuv6JzuIEEAIQAg"; // <GPGSID>
        public const string achievement_dont_forget_your_mask = "CgkIuv6JzuIEEAIQCQ"; // <GPGSID>
        public const string achievement_see_double = "CgkIuv6JzuIEEAIQAw"; // <GPGSID>
        public const string achievement_ghost_are_you_there = "CgkIuv6JzuIEEAIQBA"; // <GPGSID>
        public const string achievement_fatal_burn = "CgkIuv6JzuIEEAIQCg"; // <GPGSID>
        public const string achievement_eternal_rest = "CgkIuv6JzuIEEAIQBg"; // <GPGSID>
        public const string achievement_whos_the_craziest = "CgkIuv6JzuIEEAIQCw"; // <GPGSID>

}

